version: "3"
services:
  orders:
    build: ./orders
    restart: always
    hostname: orders
    env_file:
      - .env
    depends_on:
      - nats
      - orders_db
  orders_db:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Str0000ngPassword!
      MONGO_INITDB_DATABASE: orders
      MONGO_USER: orders
      MONGO_PASSWORD: Password123
    ports:
      - 27017:27017
    volumes:
      - "./db/orders-data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
  products:
    build: ./products
    restart: always
    hostname: products
    env_file:
      - .env
    depends_on:
      - nats
      - products_db
  products_db:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Str0000ngPassword!
      MONGO_INITDB_DATABASE: products
      MONGO_USER: products
      MONGO_PASSWORD: Password123
    ports:
      - 27018:27017
    volumes:
      - "./db/products-data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
  nats:
    image: "nats:latest"
    restart: always
    entrypoint: ["nats-server", "-DV"]
    ports:
      - 4222:4222
      - 8222:8222
