version: "3"
services:
  orders:
    build: ./orders
    restart: always
    hostname: orders
    env_file:
      - .env
  orders_db:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Str0000ngPassword!
      MONGO_INITDB_DATABASE: orders
      MONGO_USER: orders
      MONGO_PASSWORD: Password123
    ports:
      - 27017:27017
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
  nats:
    image: "nats:latest"
    restart: always
    ports:
      - 4222:4222
